idf_component_register(SRCS
                        "config.c"
                        "digipot.c"
                        "fft.c"
                        "main.c"
                        "mic.c"
                        "leds.c"
                        "led_strip_encoder.c"
                        INCLUDE_DIRS ".")
